version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '80:80' 

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - '3000:3000'
